//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.23 at 01:13:06 PM PDT 
//


package org.srs.jobcontrol.gridEngine.qstat;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for queue_info_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="queue_info_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Queue-List" type="{http://gridengine.sunsource.net/source/browse/*checkout*<!---->/gridengine/source/dist/util/resources/schemas/qstat/qstat.xsd?revision=1.11}queue_list_t" minOccurs="0"/>
 *         &lt;element name="job_list" type="{http://gridengine.sunsource.net/source/browse/*checkout*<!---->/gridengine/source/dist/util/resources/schemas/qstat/qstat.xsd?revision=1.11}job_list_t" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "queue_info_t", propOrder = {
    "queueListAndJobList"
})
public class QueueInfoT {

    @XmlElements({
        @XmlElement(name = "Queue-List", type = QueueListT.class),
        @XmlElement(name = "job_list", type = JobListT.class)
    })
    protected List<Object> queueListAndJobList;

    /**
     * Gets the value of the queueListAndJobList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the queueListAndJobList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQueueListAndJobList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QueueListT }
     * {@link JobListT }
     * 
     * 
     */
    public List<Object> getQueueListAndJobList() {
        if (queueListAndJobList == null) {
            queueListAndJobList = new ArrayList<Object>();
        }
        return this.queueListAndJobList;
    }

}
